name: prerelease-on-pr

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prerelease:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install deps
        run: npm ci

      - name: Compute prerelease version
        id: version
        run: |
          node scripts/compute-version.js --pre pr --suffix "${{ github.run_number }}" > .version
          { echo "value=$(cat .version)"; } >> "$GITHUB_OUTPUT"

      - name: Build and package
        env:
          BKTIDE_VERSION: ${{ steps.version.outputs.value }}
        run: |
          npm run package

      - name: Generate changelog body
        id: changelog
        shell: bash
        run: |
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.sha }}"
          BODY=$(git log --pretty=format:'- %s' "$BASE_SHA".."$HEAD_SHA")
          if [ -z "$BODY" ]; then BODY="Automated prerelease"; fi
          { echo "body<<EOF"; echo "$BODY"; echo "EOF"; } >> "$GITHUB_OUTPUT"

      - name: Create prerelease tag
        run: |
          VERSION=${{ steps.version.outputs.value }}
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag -a "v$VERSION" -m "Prerelease v$VERSION"
          git push origin "v$VERSION"

      - name: Create GitHub Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.value }}
          prerelease: true
          files: |
            pkg/*.alfredworkflow
            pkg/*.sha256
          body: ${{ steps.changelog.outputs.body }}

